use mydatabase;

update country_area_continent set continent_name='Asia' where 
country_name in ('Afghanistan',
'Bahrain',
'Bangladesh',
'Bhutan',
'Brunei',
'Burma',
'Cambodia',
'China',
'East Timor',
'Gaza Strip',
'Hong Kong',
'India',
'Indonesia',
'Iran',
'Iraq',
'Israel',
'Japan',
'Jordan',
'Kazakhstan',
'Korea North',
'Korea South',
'Kuwait',
'Kyrgyzstan',
'Laos',
'Lebanon',
'Macau',
'Malaysia',
'Maldives',
'Mongolia',
'Nepal',
'Oman',
'Pakistan',
'Philippines',
'Qatar',
'Russian Federation',
'Saudi Arabia',
'Singapore',
'Sri Lanka',
'Syria',
'Taiwan',
'Tajikistan',
'Thailand',
'Timor-Leste',
'Turkey',
'Turkmenistan',
'United Arab Emirates',
'Uzbekistan',
'Vietnam',
'West Bank',
'Yemen');

update country_area_continent set continent_name='Europe' where 
country_name in
('Albania',
'Andorra',
'Armenia',
'Austria',
'Azerbaijan',
'Belarus',
'Belgium',
'Bosnia and Herzegovina',
'Bulgaria',
'Croatia',
'Cyprus',
'Czech Republic',
'Czechia',
'Denmark',
'Estonia',
'Faroe Islands',
'Finland',
'France',
'Georgia',
'Germany',
'Gibraltar',
'Greece',
'Guernsey',
'Hungary',
'Iceland',
'Ireland',
'Isle of Man',
'Italy',
'Jersey',
'Kosovo',
'Latvia',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Macedonia',
'Malta',
'Moldova',
'Monaco',
'Montenegro',
'Netherlands',
'Norway',
'Poland',
'Portugal',
'Romania',
'Russia',
'San Marino',
'Serbia',
'Slovakia',
'Slovenia',
'Spain',
'Sweden',
'Switzerland',
'Ukraine',
'United Kingdom',
'Vatican City');

update country_area_continent set continent_name='Africa' where 
country_name in
('Algeria',
'Angola',
'Benin',
'Botswana',
'Burkina',
'Burundi',
'Burkina Faso',
'Cabo Verde',
'Cameroon',
'Cape Verde',
'Central African Republic',
'Chad',
'Comoros',
'Congo (Brazzaville)',
'Congo, Democratic Republic of',
'Congo (Kinshasa)',
"cote d'Ivoire",
'Djibouti',
'Egypt',
'Equatorial Guinea',
'Eritrea',
'Ethiopia',
'Gabon',
'Gambia The',
'Ghana',
'Guinea',
'Guinea-Bissau',
'Ivory Coast',
'Kenya',
'Lesotho',
'Liberia',
'Libya',
'Madagascar',
'Malawi',
'Mali',
'Mauritania',
'Mauritius',
'Morocco',
'Mozambique',
'Namibia',
'Niger',
'Nigeria',
'Rwanda',
'Saint Helena',
'Sao Tome and Principe',
'Senegal',
'Seychelles',
'Sierra Leone',
'Somalia',
'South Africa',
'South Sudan',
'Sudan',
'Swaziland',
'Tanzania',
'Togo',
'Tunisia',
'Uganda',
'Western Sahara',
'Zambia',
'Zimbabwe');

update country_area_continent set continent_name='North America' where 
country_name in
('Antigua and Barbuda',
'Anguilla',
'Bahamas The',
'Barbados',
'Belize',
'Bermuda',
'Canada',
'Cayman Islands',
'Costa Rica',
'Cuba',
'Dominica',
'Dominican Republic',
'El Salvador',
'Grenada',
'Greenland',
'Guatemala',
'Haiti',
'Honduras',
'Jamaica',
'Mexico',
'Montserrat',
'Nicaragua',
'Panama',
'Puerto Rico',
'Saint Barthelemy',
'Saint Kitts and Nevis',
'Saint Lucia',
'Saint Martin',
'Saint Pierre and Miquelon',
'Saint Vincent and the Grenadines',
'Sint Maarten',
'Trinidad and Tobago',
'Turks and Caicos Islands',
'United States',
'Virgin Islands British',
'Virgin Islands U.S.');

update country_area_continent set continent_name='Oceania' where 
country_name in
('Australia',
'Cook Islands',
'Guam',
'Fiji',
'French Polynesia',
'Kiribati',
'Marshall Islands',
'Micronesia Federated States of',
'Nauru',
'New Caledonia',
'New Zealand',
'Northern Mariana Islands',
'Palau',
'Papua New Guinea',
'American Samoa',
'Solomon Islands',
'Tonga',
'Tuvalu',
'Vanuatu',
'Wallis and Futuna');

update country_area_continent set continent_name='South America' where 
country_name in
('Argentina',
'Aruba',
'Bolivia',
'Brazil',
'Chile',
'Colombia',
'Curacao',
'Ecuador',
'Guyana',
'Paraguay',
'Peru',
'Suriname',
'Uruguay',
'Venezuela');

select * from myapp_midyear_population where continent_name='abc';