# Generated by Django 3.0.3 on 2020-03-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_midyear_population'),
    ]

    operations = [
        migrations.DeleteModel(
            name='midyear_population',
        ),
    ]
