# Generated by Django 3.0.3 on 2020-03-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_countrypopulation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryPopulation',
        ),
    ]
