# Generated by Django 3.0.3 on 2020-03-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_delete_countrypopulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=40)),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
            options={
                'db_table': 'country_population',
            },
        ),
    ]
