# Generated by Django 3.0.3 on 2020-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_countryareacontinent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryareacontinent',
            name='id',
        ),
        migrations.AlterField(
            model_name='countryareacontinent',
            name='country_code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
