# Generated by Django 3.0.3 on 2020-03-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_auto_20200312_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
            options={
                'db_table': 'continent_population',
            },
        ),
    ]
