# Generated by Django 3.0.3 on 2020-03-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_continentpopulation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContinentPopulation',
        ),
    ]
