# Generated by Django 3.0.3 on 2020-03-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_continentpopulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='worldPopulation',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('population', models.BigIntegerField()),
            ],
            options={
                'db_table': 'world_population',
            },
        ),
    ]
