# Generated by Django 3.0.3 on 2020-03-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_worldpopulation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='midyear_population',
        ),
        migrations.DeleteModel(
            name='midyear_population2',
        ),
    ]
