# Generated by Django 3.0.3 on 2020-03-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_birthdeathgrowthrates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='birthdeathgrowthrates',
            table='birth_death_growth_rates',
        ),
    ]
