# Generated by Django 3.0.3 on 2020-03-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_auto_20200319_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDeathGrowthRates',
        ),
    ]
