# Generated by Django 3.0.3 on 2020-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_birthdeathgrowthrates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeSpecificFertilityRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('fertility_rate_15_19', models.FloatField()),
                ('fertility_rate_20_24', models.FloatField()),
                ('fertility_rate_25_29', models.FloatField()),
                ('fertility_rate_30_34', models.FloatField()),
                ('fertility_rate_35_39', models.FloatField()),
                ('fertility_rate_40_44', models.FloatField()),
                ('fertility_rate_45_49', models.FloatField()),
                ('total_fertility_rate', models.FloatField()),
                ('gross_reproduction_rate', models.FloatField()),
                ('sex_ratio_at_birth', models.FloatField()),
            ],
            options={
                'db_table': 'age_specific_fertility_rates',
            },
        ),
    ]
