# Generated by Django 3.0.3 on 2020-03-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_midyearpopulationagesex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MidyearPopulationAgeSex',
        ),
    ]
