# Generated by Django 3.0.3 on 2020-03-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_midyearpopulationagesex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityLifeExpectancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('infant_mortality', models.FloatField()),
                ('infant_mortality_male', models.FloatField()),
                ('infant_mortality_female', models.FloatField()),
                ('life_expectancy', models.FloatField()),
                ('life_expectancy_male', models.FloatField()),
                ('life_expectancy_female', models.FloatField()),
                ('mortality_rate_under_5', models.FloatField()),
                ('mortality_rate_under_5_male', models.FloatField()),
                ('mortality_rate_under_5_female', models.FloatField()),
                ('mortality_rate_1_to_4', models.FloatField()),
                ('mortality_rate_1_to_4_male', models.FloatField()),
                ('mortality_rate_1_to_4_female', models.FloatField()),
            ],
            options={
                'db_table': 'mortality_life_expectancy',
            },
        ),
    ]
