# Generated by Django 3.0.3 on 2020-03-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0030_mortalitylifeexpectancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryAreaContinent',
        ),
    ]
