# Generated by Django 3.0.3 on 2020-03-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_delete_countryareacontinent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAreaContinent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('country_area', models.BigIntegerField()),
                ('continent_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'country_area_continent',
            },
        ),
    ]
